package prompts

import (
	"fmt"
	"nolvegen/internal/models"
)

// registerOutlineGenPrompts registers all outline generation prompts
func registerOutlineGenPrompts(pm *PromptManager) {
	pm.Register(&PromptTemplate{
		Skill:        SkillOutlineGen,
		Name:         "with_structure",
		Description:  "Generate outline with predefined structure",
		SystemPrompt: outlineGenSystemPrompt,
		OutputFormat: FormatJSON,
		OutputModel:  models.Outline{}, // Auto-generate schema from struct
	})
}

// buildOutlineGenUserPrompt builds user prompt for outline generation
func buildOutlineGenUserPrompt(data map[string]interface{}) string {
	parts, _ := data["parts"].(int)
	volumes, _ := data["volumes"].(int)
	chapters, _ := data["chapters"].(int)
	language, _ := data["language"].(string)

	langName := "the specified language"
	if language == "zh" {
		langName = "Chinese"
	} else if language == "en" {
		langName = "English"
	}

	return fmt.Sprintf("Generate a complete story outline with exactly %d parts, %d volumes per part, and %d chapters per volume. ALL content must be in %s.",
		parts, volumes, chapters, langName)
}

// BuildOutlineGenData builds data for outline generation prompt
func BuildOutlineGenData(structure models.StoryStructure, setup *models.StorySetup, language string) map[string]interface{} {
	// Use StructToPrompt to convert StorySetup to formatted string
	setupPrompt := StructToPrompt(setup, "")

	return map[string]interface{}{
		"parts":          structure.TargetParts,
		"volumes":        structure.TargetVolumes,
		"chapters":       structure.TargetChapters,
		"total_chapters": structure.TotalChapters(),
		"setup":          setupPrompt,
		"language":       language,
	}
}

const outlineGenSystemPrompt = `You are a professional novel outlining assistant.
Your task is to generate a detailed story outline based on the story setup provided.

STRICT STRUCTURE REQUIREMENTS:
- You MUST generate exactly {{parts}} parts
- Each part MUST have exactly {{volumes}} volumes
- Each volume MUST have exactly {{chapters}} chapters
- Total chapters: {{total_chapters}}

The outline must follow a strict 3-level structure: Parts → Volumes → Chapters.

Story Setup Information:
{{setup}}

ID Format (IMPORTANT - IDs will be auto-generated by code, you can leave them empty or use simple placeholders):
- Part ID: P{number} (e.g., P1, P2)
- Volume ID: P{part}-V{volume} (e.g., P1-V1, P2-V3)
- Chapter ID: P{part}-V{volume}-C{chapter} (e.g., P1-V1-C1, P2-V3-C5)

Chapter Summary Format:
- Summary MUST follow this format: "角色 在 什么地方 发生了 什么事"
- Example: "李明 在 废弃工厂 发现了 秘密实验室"

Chapter Event Types (track all significant changes):
1. relationship - Character relationship changes (e.g., allies become enemies, romance begins)
   - Characters: [characterA, characterB]
   - Subject: relationship name/type
   - Change: description of how relationship changed
2. goal - Character goal updates (e.g., new objective, goal achieved, goal abandoned)
   - Characters: [character]
   - Subject: goal description
   - Change: new/achieved/abandoned/changed
3. item - Character acquires or loses important items
   - Characters: [character]
   - Subject: item name
   - Change: get/lost/damaged
4. premise - Character progression system updates (e.g., mecha upgrade, gene evolution)
   - Characters: [character]
   - Subject: premise name (e.g., "机甲系统")
   - Change: level up/new ability/breakthrough
5. storyline - Storyline progress updates
   - Characters: []
   - Subject: storyline name
   - Change: started/advanced/completed/twist

CRITICAL CONTINUITY REQUIREMENTS:
1. CAUSAL CHAIN: Each chapter MUST be a direct consequence of the previous chapter's events. Ask "What happens BECAUSE of what happened before?"
2. EVENT TRACKING: Use the Events field to track ALL state changes. The next chapter should reference these changes in its summary and beats.
3. CHARACTER STATE: Characters' emotional states, goals, and relationships must evolve naturally across chapters. Don't reset character development.
4. PLOT THREADS: Storylines should progress gradually. A storyline started in chapter 1 should show advancement in subsequent chapters, not disappear.
5. CLIFFHANGERS & HOOKS: Chapters should end with hooks that lead into the next chapter, creating narrative momentum.
6. RECURRING ELEMENTS: Locations, items, and relationships mentioned in one chapter should reappear naturally in later chapters when relevant.

Guidelines:
- Follow the EXACT structure specified above
- Ensure the outline follows a coherent narrative arc across all parts
- Include specific plot beats for each chapter (3-5 beats per chapter)
- Vary the pacing (slow/normal/fast) based on the story needs
- Make conflicts clear and compelling
- Each part should have a clear narrative purpose
- Each volume should advance the story within its part
- Each chapter should have clear progression
- INCORPORATE the storylines into the outline naturally
- USE the premises and progression systems in the plot (e.g., characters should advance through the progression stages at appropriate points in the story)
- TRACK all significant changes using Events (relationships, goals, items, premise progress, storyline updates)
- ENSURE CONTINUITY: When writing chapter N, always reference what happened in chapter N-1 and set up what should happen in chapter N+1`
