package prompts

import (
	"fmt"
	"novelgen/internal/models"
)

// registerOutlineGenPrompts registers all outline generation prompts
func registerOutlineGenPrompts(pm *PromptManager) {
	pm.Register(&PromptTemplate{
		Skill:        SkillOutlineGen,
		Name:         "with_structure",
		Description:  "Generate outline with predefined structure",
		SystemPrompt: outlineGenSystemPrompt,
		OutputFormat: FormatJSON,
		OutputModel:  models.Outline{}, // Auto-generate schema from struct
	})
}

// buildOutlineGenUserPrompt builds user prompt for outline generation
func buildOutlineGenUserPrompt(data map[string]interface{}) string {
	parts, _ := data["parts"].(int)
	volumes, _ := data["volumes"].(int)
	chapters, _ := data["chapters"].(int)
	language, _ := data["language"].(string)

	langName := "the specified language"
	if language == "zh" {
		langName = "Chinese"
	} else if language == "en" {
		langName = "English"
	}

	return fmt.Sprintf("Generate a complete story outline with exactly %d parts, %d volumes per part, and %d chapters per volume. ALL content must be in %s.",
		parts, volumes, chapters, langName)
}

// BuildOutlineGenData builds data for outline generation prompt
func BuildOutlineGenData(structure models.StoryStructure, setup *models.StorySetup, language string) map[string]interface{} {
	// Use StructToPrompt to convert StorySetup to formatted string
	setupPrompt := StructToPrompt(setup, "")

	summaryFormat := "Summary MUST be ONE sentence following: CHARACTER in LOCATION attempts ACTION, but OBSTACLE/STAKE. Example: Maya in a ruined observatory discovers a hidden chamber but triggers a security lockdown."
	if language == "zh" {
		summaryFormat = "Summary MUST be ONE sentence following: 角色 在 什么地方 做了 什么事，却 遇到 什么阻碍/代价。Example: 李明 在 废弃工厂 发现了 秘密实验室，却 引爆了 警报。"
	} else if language != "en" {
		summaryFormat = "Summary MUST be ONE sentence following: CHARACTER in LOCATION attempts ACTION, but OBSTACLE/STAKE (translate into the target language). Example: Maya in a ruined observatory discovers a hidden chamber but triggers a security lockdown."
	}

	return map[string]interface{}{
		"parts":          structure.TargetParts,
		"volumes":        structure.TargetVolumes,
		"chapters":       structure.TargetChapters,
		"total_chapters": structure.TotalChapters(),
		"setup":          setupPrompt,
		"language":       language,
		"summary_format": summaryFormat,
	}
}

const outlineGenSystemPrompt = `You are a professional novel outlining assistant.
Your task is to generate a detailed story outline based on the story setup provided.

STRICT STRUCTURE REQUIREMENTS:
- You MUST generate exactly {{parts}} parts
- Each part MUST have exactly {{volumes}} volumes
- Each volume MUST have exactly {{chapters}} chapters
- Total chapters: {{total_chapters}}

The outline must follow a strict 3-level structure: Parts → Volumes → Chapters.

Story Setup Information:
{{setup}}

ID Format (IMPORTANT - IDs will be auto-generated by code, you can leave them empty or use simple placeholders):
- Part ID: P{number} (e.g., P1, P2)
- Volume ID: P{part}-V{volume} (e.g., P1-V1, P2-V3)
- Chapter ID: P{part}-V{volume}-C{chapter} (e.g., P1-V1-C1, P2-V3-C5)

Chapter Summary Format:
- {{summary_format}}

Chapter Field Requirements:
- Summary character(s) MUST appear in Characters list
- Location MUST match the summary location and cannot be empty
- Conflict MUST be one concise sentence that states the immediate opposing force or dilemma
- Pacing MUST be one of: slow, normal, fast
- opening_beat MUST match beats[0] and directly continue from the previous chapter's final beat
- closing_beat MUST match beats[last] and set up the next chapter's opening beat
- state_change MUST be a one-sentence primary change that maps to one concrete Events entry

Chapter Event Types (track all significant changes):
1. relationship - Character relationship changes (e.g., allies become enemies, romance begins)
   - Characters: [characterA, characterB]
   - Subject: relationship name/type
   - Change: description of how relationship changed
2. goal - Character goal updates (e.g., new objective, goal achieved, goal abandoned)
   - Characters: [character]
   - Subject: goal name/description (required when resolving a goal)
   - Change: use the exact goal description when introducing/updating; use only "achieved" or "abandoned" when resolving (and then Subject MUST name the resolved goal)
3. item - Character acquires or loses important items
   - Characters: [character]
   - Subject: item name
   - Change: get/lost (use lost for destroyed or removed items)
4. premise - Character progression system updates (e.g., mecha upgrade, gene evolution)
   - Characters: [character]
   - Subject: premise name (e.g., "机甲系统")
   - Change: level up/new ability/breakthrough
5. storyline - Storyline progress updates
   - Characters: []
   - Subject: storyline name
   - Change: started/advanced/completed/twist
   - Details: ONE SENTENCE describing what happened (e.g., "主角发现了矿场深处的秘密通道", "林砚和阿石达成了临时同盟", "反派抢走了关键道具")
6. gate - Immediate obstacle, cost, or setback introduced in the chapter
   - Characters: [character]
   - Subject: obstacle or stake name (e.g., "sealed vault", "time limit", "wounded ally")
   - Change: introduced/escalated/overcome

CRITICAL CONTINUITY REQUIREMENTS:
1. CAUSAL CHAIN: Each chapter MUST be a direct consequence of the previous chapter's events. Ask "What happens BECAUSE of what happened before?"
2. EVENT TRACKING: Use the Events field to track ALL state changes. The next chapter should reference these changes in its summary and beats.
3. CHARACTER STATE: Characters' emotional states, goals, and relationships must evolve naturally across chapters. Don't reset character development.
4. PLOT THREADS: Storylines should progress gradually. A storyline started in chapter 1 should show advancement in subsequent chapters, not disappear.
5. CLIFFHANGERS & HOOKS: Chapters should end with hooks that lead into the next chapter, creating narrative momentum.
6. RECURRING ELEMENTS: Locations, items, and relationships mentioned in one chapter should reappear naturally in later chapters when relevant.
7. BEAT CONTINUITY (VERY IMPORTANT):
   - The LAST beat of chapter N and the FIRST beat of chapter N+1 MUST be directly connected
   - Example: If chapter 1 ends with "主角修炼到天亮", chapter 2 MUST start with "天亮了，主角结束修炼"
   - Example: If chapter 1 ends with "主角被敌人包围", chapter 2 MUST start with "主角面对包围，准备突围"
   - NEVER have time jumps or scene changes between the last beat of one chapter and the first beat of the next
   - The first beat of each chapter (except chapter 1) MUST explicitly continue from the final moment of the previous chapter
   - opening_beat MUST equal beats[0]; closing_beat MUST equal beats[last]

Guidelines:
- Follow the EXACT structure specified above
- Ensure the outline follows a coherent narrative arc across all parts
- Include specific plot beats for each chapter (3-5 beats per chapter)
- Beats must alternate intention → obstacle → consequence (no three beats in a row without a complication)
- The final beat of each chapter MUST introduce a concrete obstacle or decision that the next chapter resolves or escalates
- Vary the pacing (slow/normal/fast) based on the story needs
- Make conflicts clear and compelling
- Each part should have a clear narrative purpose
- Each volume should advance the story within its part
- Each chapter should have clear progression
- INCORPORATE the storylines into the outline naturally
- USE the premises and progression systems in the plot (e.g., characters should advance through the progression stages at appropriate points in the story)
- TRACK all significant changes using Events (relationships, goals, items, premise progress, storyline updates)
- ENSURE CONTINUITY: When writing chapter N, always reference what happened in chapter N-1 and set up what should happen in chapter N+1
- Beats MUST begin with a continuation from the previous chapter's final beat ("Therefore,") or the prior beat ("Then,") to enforce causal flow
- For each chapter, ensure at least ONE event entry reflects the chapter's core change (relationship/goal/item/premise/storyline/gate) so state tracking remains usable
- state_change MUST be mirrored by exactly one concrete Events entry (same change described)
- When a chapter introduces a new obstacle or cost, add a gate event to record it`
